<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-04-30T20:06:56+03:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.1.0',
    'version_db_installed' => '20170123000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1493494947,
        'latest_version' => '8.1.0',
        'do_page_reindex_check' => false,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
