<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-04-29T22:37:03+03:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Maksym',
        ],
    ],
];
